manifest:
  remotes:
    - name: doctorcooper
      url-base: https://github.com/doctorcooper
  projects:
    - name: zmk
      remote: doctorcooper
      revision: dao-keyboard
      import: app/west.yml
  self:
    path: config
